title: 동환의 기록
email: founder@altamirasoft.com
description: >-
  일과 사업, 가족, 시행착오와 배움을 기록하는 개인 블로그
baseurl: ""
url: "https://bdhwan.github.io"
twitter_username: bdhwan
github_username: bdhwan
theme: minima
plugins:
  - jekyll-feed
  - jekyll-analytics

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true

jekyll_analytics:
  GoogleAnalytics:
    id: UA-28403131-1
    anonymizeIp: false
